version: '3.8'

services:
  openmanus:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openmanus
    volumes:
      # Mount the local directory to allow for development without rebuilding
      - ./:/app
      # Mount a data directory for persistent storage
      - ./data:/app/data
    ports:
      # Map container ports to host - adjust based on the application's needs
      - "7860:7860"  # For Gradio web UI
      - "8000:8000"  # For API server
    environment:
      # Environment variables - add or modify as needed
      - MODEL_DIR=/app/models
      - PYTHONPATH=/app
      # Uncomment if using CUDA
      # - CUDA_VISIBLE_DEVICES=0
    # Uncomment for GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    restart: unless-stopped
    # Uncomment and adjust the command as needed
    # command: python -m openmanus.serve
